### ISSUE TITLE
Welcome Universidad de Colima!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/universidad-de-colima#1]
Hello! Issues work on GitHub in a way that lets people comment about the project or file any complaints they may have.

In this repository, feel free to comment on this issue to let me know that you want to participate. I'll add people as collaborators once you comment.

**Comment by alexismellamo** [comment]
Hi, I like trains.

**Comment by diegoavalos95** [comment]
hi

**Comment by neto3000** [comment]
Hi there , I'm ernesto :v:

**Comment by DeadKennedyx** [comment]
Sup

**Comment by FcoMondro** [comment]
Hello :+1: 
I'm Francisco

**Comment by chukitow** [comment]
Hi dude, I'm Ivan :)

**Comment by KarlyGrCm** [comment]
Hi!I'm Karly :smile:

**Comment by roberbnd** [comment]
Hi

**Comment by FerPerales** [comment]
I like turtles 🐢

**Comment by DarkAbsolutE** [comment]
Hi, my name is Cristian :dango:

**Comment by ChristianAnderson** [comment]
Hi! Could you add me please?

**Comment by caesolrac** [comment]
Hi, My name is :v

**Comment by githubteacher** [comment]
Everyone should be added!
